/**
 * WdkProvider
 *
 * Bootstraps the WDK layer on app start:
 *  1. Reads the wallet registry from Keychain (no biometric prompt).
 *  2. Builds ManagedWallet metadata for every registered walletId.
 *  3. Populates the Redux wallets list + sets the active wallet.
 *  4. Updates Redux auth state so the RootNavigator knows whether a wallet
 *     exists (→ UnlockScreen) or it's a fresh install (→ SetupScreen).
 *
 * This provider does NOT use @tetherto/wdk-react-native-core's WdkAppProvider
 * because that requires a compiled worklet bundle generated by the
 * wdk-worklet-bundler CLI.  Instead, we run the same cryptographic operations
 * directly on the main thread using @scure/bip39 + @scure/bip32 — the same
 * pure-JS libraries used by the WDK worklet internally.
 */

import React, { createContext, useContext, useEffect, useState } from 'react';
import { useAppDispatch } from '../../store/hooks';
import {
  setManagedWallets,
  setActiveWallet,
} from '../../store/slices/walletSlice';
import { setAuthenticated, setInitialised } from '../../store/slices/authSlice';
import { walletStorageService } from '../../core/api/walletStorageService';
import type { ManagedWallet } from '../../core/api/wdkService';

// ─── Context value ────────────────────────────────────────────────────────────

interface WdkContextValue {
  /** True once the bootstrap check has finished. */
  isReady: boolean;
  /** True if at least one wallet is registered in the keychain. */
  hasWallet: boolean;
}

const WdkContext = createContext<WdkContextValue>({
  isReady: false,
  hasWallet: false,
});

export function useWdkContext(): WdkContextValue {
  return useContext(WdkContext);
}

// ─── Provider ─────────────────────────────────────────────────────────────────

interface WdkProviderProps {
  children: React.ReactNode;
}

/**
 * Mount ONCE at the app root, inside the Redux <Provider>.
 */
export const WdkProvider: React.FC<WdkProviderProps> = ({ children }) => {
  const dispatch = useAppDispatch();
  const [state, setState] = useState<WdkContextValue>({
    isReady: false,
    hasWallet: false,
  });

  useEffect(() => {
    let cancelled = false;

    async function bootstrap() {
      try {
        const ids = await walletStorageService.listWalletIds();

        if (cancelled) return;

        if (ids.length > 0) {
          // Reconstruct ManagedWallet metadata from stored IDs.
          // The address cannot be re-derived without the mnemonic (which would
          // trigger a biometric prompt) so we leave it empty for the list view
          // — the active wallet screen loads full details after unlock.
          const wallets: ManagedWallet[] = ids.map(id => ({
            id,
            name: id,
            address: '', // populated after biometric unlock
            network: 'ethereum' as const,
            createdAt: 0, // no timestamp stored at this layer
          }));

          dispatch(setManagedWallets(wallets));
          dispatch(setActiveWallet(ids[0]));
          dispatch(setAuthenticated(true));

          setState({ isReady: true, hasWallet: true });
        } else {
          setState({ isReady: true, hasWallet: false });
        }
      } catch {
        // Even on error, mark as initialised so the app can show the setup flow
        setState({ isReady: true, hasWallet: false });
      } finally {
        if (!cancelled) {
          dispatch(setInitialised(true));
        }
      }
    }

    bootstrap();
    return () => {
      cancelled = true;
    };
  }, [dispatch]);

  return <WdkContext.Provider value={state}>{children}</WdkContext.Provider>;
};
