/**
 * WDK Bundle Configuration
 * Generated by @tetherto/wdk-worklet-bundler
 *
 * For documentation see: https://github.com/tetherto/wdk-worklet-bundler
 */

module.exports = {
  // Network mappings
  // Map logical network names to WDK wallet packages
  networks: {
    ethereum: { package: '@tetherto/wdk-wallet-evm-erc-4337' }
  },

  // Output paths (optional, defaults shown)
  output: {
    bundle: './.wdk-bundle/wdk-worklet.bundle.js',
    types: './.wdk/index.d.ts'
  },

  // Build options (optional)
  options: {
    // minify: false,
    // sourceMaps: false,
    targets: ['ios-arm64','ios-arm64-simulator','ios-x64-simulator','android-arm64','android-arm','android-arm64','android-ia32','android-x64']
    // targets: ['ios-arm64']
  }
};
