/**
 * WDK Worklet Bundle Loader
 *
 * Imports the pre-built worklet bundle generated by `wdk-worklet-bundler`.
 * This file is generated in .wdk-bundle/ by running:
 *   npx wdk-worklet-bundler generate
 *
 * The bundle is a self-contained Bare JS binary that runs in a separate
 * thread via react-native-bare-kit. It handles all cryptographic and
 * network operations off the UI thread.
 */

// eslint-disable-next-line @typescript-eslint/no-var-requires
const bundle = require('../../../.wdk-bundle/wdk-worklet.bundle.js') as string;

export default bundle;
